//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Core.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Id_Producto { get; set; }
        public int Id_Tipo { get; set; }
        public string Nombre_Producto { get; set; }
        public string Clave_Producto { get; set; }
        public int Tipo_Producto { get; set; }
        public int Existencia_Producto { get; set; }
    }
}
