//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Core.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Producto
    {
        public int Id_Tipo { get; set; }
        public string Tipo_Producto1 { get; set; }
    }
}
