//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id_Pedido { get; set; }
        public int Id_cliente { get; set; }
        public System.DateTime Fecha_Pedido { get; set; }
        public int Id_Producto { get; set; }
        public int Id_Vendedor { get; set; }
        public int Cantidad_Producto1 { get; set; }
        public string TotalPrecio_Producto { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
