//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public int Id_Vendedor { get; set; }
        public string Nombre_Vendedor { get; set; }
        public string Telefono_Vendedor { get; set; }
        public string Correo_Vendedor { get; set; }
    }
}
